# Generated by Django 5.0.7 on 2024-07-26 01:45

import portfolio.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', models.TextField()),
                ('about_us_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_address', models.TextField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=15)),
                ('contact_map', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_image', models.ImageField(blank=True, default='media/uploads/slider/default.png', error_messages={'empty': 'Please upload an image file', 'invalid': 'Image files only', 'invalid_image': 'Upload a valid image. The file you uploaded was either not an image or a corrupted image.', 'max_length': 'This image has a very large file size. Please upload an image with a smaller file size.', 'missing': 'No image file was found'}, help_text='Upload a team image', null=True, upload_to='media/uploads/slider/', validators=[portfolio.validators.validate_image], verbose_name='Team Image')),
                ('slider_title', models.CharField(max_length=255)),
                ('slider_description', models.TextField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=99)),
                ('menu_detail', models.CharField(max_length=999)),
                ('menu_price', models.PositiveIntegerField()),
                ('menu_image', models.ImageField(blank=True, default='media/uploads/menu/default.jpg', error_messages={'empty': 'Please upload an image file', 'invalid': 'Image files only', 'invalid_image': 'Upload a valid image. The file you uploaded was either not an image or a corrupted image.', 'max_length': 'This image has a very large file size. Please upload an image with a smaller file size.', 'missing': 'No image file was found'}, help_text='Upload a menu image', null=True, upload_to='media/uploads/menu/', validators=[portfolio.validators.validate_image], verbose_name='Menu Image')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_name', models.CharField(max_length=255)),
                ('reservation_email', models.EmailField(max_length=254)),
                ('reservation_phone', models.CharField(max_length=15)),
                ('reservation_date', models.DateField()),
                ('reservation_time', models.TimeField()),
                ('reservation_guests', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=99)),
                ('team_position', models.CharField(max_length=99)),
                ('team_image', models.ImageField(blank=True, default='media/uploads/team/default.png', error_messages={'empty': 'Please upload an image file', 'invalid': 'Image files only', 'invalid_image': 'Upload a valid image. The file you uploaded was either not an image or a corrupted image.', 'max_length': 'This image has a very large file size. Please upload an image with a smaller file size.', 'missing': 'No image file was found'}, help_text='Upload a team image', null=True, upload_to='media/uploads/team/', validators=[portfolio.validators.validate_image], verbose_name='Team Image')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial_name', models.CharField(max_length=255)),
                ('testimonial_details', models.TextField()),
                ('testimonial_image', models.ImageField(blank=True, default='media/uploads/testimonial/default.png', error_messages={'empty': 'Please upload an image file', 'invalid': 'Image files only', 'invalid_image': 'Upload a valid image. The file you uploaded was either not an image or a corrupted image.', 'max_length': 'This image has a very large file size. Please upload an image with a smaller file size.', 'missing': 'No image file was found'}, help_text='Upload a testimonial image', null=True, upload_to='media/uploads/testimonial/', validators=[portfolio.validators.validate_image], verbose_name='Testimonial Image')),
                ('testimonial_position', models.CharField(blank=True, max_length=255, null=True)),
                ('testimonial_company', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
